import "@/styles/globals.css";
import Footer from "@/components/footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Osmanlı Building",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="app">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
